level_map = [
    '                             ',
    '                             ',
    '                             ',
    ' XX     XXX          XX      ',
    ' XX                          ',
    ' XXXX          XX         XX ',
    ' XXXX        XX              ',
    ' XX     X  XXXX    XX  XX    ',
    '        X  XXXX    XX  XXXP  ',
    '     XXXX  XXXXXX  XX  XXXX  ',
    ' XXXXXXXX  XXXXXX  XX  XXXX  ',
]

level_test_1 = [
    'X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X',
    'XX X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    '                                                                                         ',
    '                                                                                         ',
    '                                           P                                             X',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X',
    'XX X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    '                                           XX                                            ',
    '                                           XX                                            ',
    '                                           XX                                            X',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X',
    'XX X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X ',
    '                                                                                          ',
    '                                                                                          ',
    '                                                                                          ',
    '                                                                                         X',
    '                                                                                         X',
    '                                           XX                                            X',
    '                                           XX                                            X',
    'X                                          XX                                            X',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
]

level_test_3 = [
    'XX                                                            ',
    ' X                                                            ',
    'XX                                                           ',
    ' X                                                           ',
    'XX                                                             ',
    ' X                                                            ',
    'XX                                                          ',
    ' X                          XXXX                          ',
    'XX               X  XXXX                                     ',
    ' X       X       X  X                                        ',
    'XX    XXXXXXX    XXXX                                        ',
    ' X                P                   X X X                 X',
    'XX            XXXXXXX       XXXXX     XXXXX     X          XX',
    ' X            X     X           XX  XXX                     X ',
    'XX       XXXXXX                 X                        XXXX',
    ' X       XXXXXX                 X   XXXXXXX                 X',
    'XX       XXXXXX                 X                    XXXX   X',
    ' XXXXXX  XXXXXX                 X                    XXXX   X',
    'XX      XXXXXXX                 X                    XXXX   X',
    ' X   XXXXXXXXXX                 X                    XXXX   X',
    'XXX     XXXXXXX                 X                    XXXX   X',
    ' XXXX  XXXXXXXX                 X                    XXXX   X',
    'XX    XXXXXXXXX                 X                    XXXX   X',
    'XXXX  XXXXXXXXX                                              ',
    ' XXXX         X                                                  ',
    'XXXXXX        X                                                   ',
    ' XXXXXX                                                          ',
    'XX               X                                           ',
    ' XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',

]

fall_test = ['XX  P  XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XX     XX',
             'X       X',
             'XXXXXXXXX'
             ]

jump_test = [
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X       X',
    'XX     XX',
    'X   P   X',
    'XXXXXXXXX'
]

tile_size = 64

screen_width = 1200
screen_height = len(level_map) * tile_size
