level_map = [
    '                             ',
    '                             ',
    '                             ',
    ' XX     XXX          XX      ',
    ' XX                          ',
    ' XXXX          XX         XX ',
    ' XXXX        XX              ',
    ' XX     X  XXXX    XX  XX    ',
    '        X  XXXX    XX  XXXP  ',
    '     XXXX  XXXXXX  XX  XXXX  ',
    ' XXXXXXXX  XXXXXX  XX  XXXX  ',
]

level_test_1 = [
    'X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X',
    'XX X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    '                                           XX                                            ',
    '                                           XX                                            ',
    '                                           XX                                            X',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X',
    'XX X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    'X                                                                                        ',
    '                                           XX                                            ',
    '                                           XX                                            ',
    '     P                                     XX                                            X',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X',
    'XX X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X ',
    '                                                                                          ',
    '                                                                                          ',
    '                                                                                          ',
    '                                                                                         X',
    '                                                                                         X',
    '                                           XX                                            X',
    '                                           XX                                            X',
    'X                                          XX                                            X',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
]

level_test_2 = [
    'X                                                                                       ',
    'X                                                                                       ',
    'X                                                                                       ',
    'X                                                                      XXXXXXX     XXXXXXX            ',
    'X                         XXXXXXX   XXXXXXX                                                           ',
    'X                                                                                       ',
    'X                                                       XXXXXXXXX                                ',
    'X        XXXXXXX                                                                               ',
    'X                  XXXXXXX                                                                     ',
    'X  P                                                                                     ',
    'X  X                                                                                       ',
    'X  X                                                                                       ',
    'X  X                                                                                       ',
    'XXXXXXXX                                                                                       ',

]

level_test_3 = [
    'XX                                                            ',
    ' X                                                            ',
    'XX                                                           ',
    ' X                                                           ',
    'XX                                                             ',
    ' X                                                            ',
    'XX                                                          ',
    ' X                             XXXX                          ',
    'XX                  XXXX                                     ',
    ' X    P X           X                                        ',
    'XX    XXXXXXX    XXXX                                        ',
    ' X                                    X X X                 X',
    'XX            XXXXXXX       XXXXX     XXXXX     X          XX',
    ' X            X     X           XX  XXX                     X ',
    'XX       XXXXXX                 X                        XXXX',
    ' X       XXXXXX                 X   XXXXXXX                 X',
    'XX       XXXXXX                 X                    XXXX   X',
    ' XXXXXX  XXXXXX                 X                    XXXX   X',
    'XX       XXXXXX                 X                    XXXX   X',
    ' X       XXXXXX                 X                    XXXX   X',
    'XX       XXXXXX                 X                    XXXX   X',
    ' X       XXXXXX                 X                    XXXX   X',
    'XX       XXXXXX                 X                    XXXX   X',

]

tile_size = 64

screen_width = 1200
screen_height = len(level_map) * tile_size
